In [3]:
import numpy as np

In [34]:
arr = np.array([10,20,30,40])
print(arr[0:3])
print(type(arr))


[10 20 30]
<class 'numpy.ndarray'>


In [39]:
arr2d = np.array([[10,20,30,40],[50,60,70,80]])
print(arr2d[0:3,0:3])
print(arr2d[0,1:3])
print(arr2d[1,1:3])

[[10 20 30]
 [50 60 70]]
[20 30]
[60 70]


In [51]:
print(np.shape(arr2d)) # rows and columns
print(np.size(arr2d))
print(np.ndim(arr2d))
print(arr2d.dtype)#datatype of array
print(len(arr2d))#number of nested values
print(arr.astype(float))#Conversion of datatype in array
print(type(arr)) # datatype of variable


(2, 4)
8
2
int64
2
[10. 20. 30. 40.]
<class 'numpy.ndarray'>


# Mathematical Operations and Function on Arrays

In [6]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1+arr2)
print(np.add(arr1,arr2))

[60 60 70 40 30]
[60 60 70 40 30]


In [7]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[  0  20  50   0 -10]
[  0  20  50   0 -10]


In [8]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[900 800 600 400 200]
[900 800 600 400 200]


In [9]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[1.  2.  6.  1.  0.5]
[1.  2.  6.  1.  0.5]


In [12]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 16  4  1]


In [17]:
arr1 = np.array([ 9,16,4,1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]


# Combining and Splitting Arrays

In [21]:
# Concatenate
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [25]:
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2],axis = 1))
print(np.concatenate([arr1,arr2],axis = 0))

[[30 40  5  5]
 [50 10  3  3]]
[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [26]:
print(np.hstack([arr1,arr2])) #horizontal Concatenation

[[30 40  5  5]
 [50 10  3  3]]


In [28]:
print(np.vstack([arr1,arr2]))#vertical Concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [35]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,2)
print(b)

[array([20, 40, 30]), array([40, 10, 20])]


# Adding and removing Element in the arrays.

In [ ]:
import numpy as np
a = np.array([20,40,60,80])
b = np.array([[20,40],[60,80]])
print(np.append(a,90))
print(np.append(b,90))


[20 40 60 80 90]
[20 40 60 80 90]
[20 50 40 60 80]


In [3]:
print(np.insert(a,1,50))  # array,index,value
print(np.insert(b,1,[50,60],axis = 0))

[20 50 40 60 80]
[[20 40]
 [50 60]
 [60 80]]


In [12]:
print(np.delete(a,1))
print(np.delete(b,1,axis=1))

[20 60 80]
[[20]
 [60]]


-> Numpy - Sort,Filter and Search

In [15]:
ar = np.array([7,8,9,4,12])
ar2 = np.array([[7,8,9,4,12],[2,8,5,1,3]])
print(np.sort(ar))
print(np.sort(ar2))

[ 4  7  8  9 12]
[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [22]:
#Search
ar = np.array([1,2,3,4,5])
s = np.where(ar%2==0)
ss = np.searchsorted(ar,5)
print(ss)

4


In [28]:
# Filter
ar = np.array([20,30,40,50])

fa = [True,False,True,False]
#new = ar[fa]
#print(new)

#fa = ar>35
#new = ar[fa]
#print(new)

fa = ar%2==0
new = ar[fa]
print(new)

[20 30 40 50]


Aggregating Function in Numpy

In [37]:
import numpy as np
a = np.array([20,40,60,70])

print(np.sum(a))

print(np.min(a))

print(np.max(a))

print(np.size(a))

print(np.mean(a))

print(np.cumsum(a))

print(np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [53]:
a  = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price,"\n",quantity)

c = np.cumprod([price,quantity],axis=0)

print(sum(c[1]))


[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
31270


STATISTICAL FUNCTIONS NUMPY

In [60]:
import numpy as np
import statistics as ststs

baked_food = [200,300,150,130,200,280,170,188]

a = np.array(baked_food)
# MEAN
print(np.mean(a)) # Sum of all the value/number of value

# MEDIAN
print(np.median(a)) # Central value after sorting

# MODE
print(ststs.mode(a)) # 

# STANDARD DEVIATION
print(np.std(a))

# Varience
print(np.var(a))

202.25
194.0
200
55.68157235567257
3100.4375


In [ ]:
# COFFICIENT OF CORELATION
# -1 - Represent inversely proportional relationship
# +1 - Represent proportional relationship
# 0 - means no relationship
tobacco_consumtion = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]

print(np.corrcoef([tobacco_consumtion,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]
